import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Plant, { PlantStatus } from './src/models/plant_model';

// Load env vars
dotenv.config();

const plantsData = [{ "nameAr": "خيار",
"nameEn": "Cucumber",
"scientificName": "Cucumis sativus",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/96/Cucumis_sativus_001.JPG",
"category": "Crops",
"careLevel": "medium",
"descriptionAr": "محصول صيفي سريع النمو ينتج ثماراً منعشة وغنية بالماء. ينجح في الشمس والتربة الخصبة مع دعم للأنواع المتسلقة والري المنتظم.",
"descriptionEn": "A fast-growing summer crop that produces refreshing, water-rich fruits. It thrives in sun and fertile soil with support for climbing types and regular watering.",
"waterRequirements": "Moderate to high - Keep soil evenly moist",
"lightRequirements": "Full sun",
"humidityRequirements": "Medium humidity, 50-70%",
"soilRequirements": "Rich, well-draining soil with compost",
"fertilizerRequirements": "Every 2 weeks during fruiting",
"growthRate": "Fast",
"matureSize": "0.5-2 meters depending on variety",
"temperatureRange": "18°C - 32°C",
"toxicityLevel": "Non-toxic; fruits are edible",
"wateringFrequency": "Every 2-3 days in hot weather",
"careInstructions": "Use trellises for climbers and harvest regularly to encourage more fruits.",
"commonProblems": "Powdery mildew, aphids, cucumber beetles, bitter fruits from stress",
"propagationMethod": "Seed",
"nativeRegion": "South Asia",
"plantBenefits": "Edible fruit, hydration, high productivity"
},
{ "nameAr": "فلفل حلو",
"nameEn": "Bell Pepper",
"scientificName": "Capsicum annuum",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/85/Green_pepper.jpg",
"category": "Crops",
"careLevel": "medium",
"descriptionAr": "محصول خضري مهم ينتج ثماراً ملونة تؤكل طازجة أو مطبوخة. يحتاج حرارة معتدلة وشمساً جيدة وتسميداً منتظماً لإنتاج ثمار ممتلئة.",
"descriptionEn": "A major vegetable crop producing colorful fruits used fresh or cooked. It needs moderate warmth, good sun, and regular feeding to produce full fruits.",
"waterRequirements": "Moderate - Keep soil evenly moist",
"lightRequirements": "Full sun",
"humidityRequirements": "Medium humidity, 50-70%",
"soilRequirements": "Fertile, well-draining loam",
"fertilizerRequirements": "Every 2-3 weeks during flowering and fruiting",
"growthRate": "Moderate",
"matureSize": "45-90 cm tall",
"temperatureRange": "18°C - 30°C",
"toxicityLevel": "Fruits edible; green parts can be irritating if ingested in large amounts",
"wateringFrequency": "2-4 times per week",
"careInstructions": "Avoid water stress during flowering and support heavy fruit loads if needed.",
"commonProblems": "Aphids, blossom drop, blossom-end rot, bacterial spot",
"propagationMethod": "Seed",
"nativeRegion": "Central and South America",
"plantBenefits": "Edible fruit, high vitamin content, versatile crop"
},
{ "nameAr": "خس",
"nameEn": "Lettuce",
"scientificName": "Lactuca sativa",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Salad_lettuce.jpg",
"category": "Crops",
"careLevel": "easy",
"descriptionAr": "محصول ورقي سريع النمو يناسب الجو المعتدل ويُزرع بكثرة في الحدائق والأحواض. يحتاج ريّاً منتظماً وتربة خفيفة ليعطي أوراقاً طرية ومقرمشة.",
"descriptionEn": "A fast-growing leafy crop suited to mild weather and commonly grown in gardens and beds. It needs regular watering and light soil to produce tender, crisp leaves.",
"waterRequirements": "Moderate - Keep soil consistently moist",
"lightRequirements": "Full sun to partial shade",
"humidityRequirements": "Medium humidity, 50-70%",
"soilRequirements": "Light, fertile, well-draining soil",
"fertilizerRequirements": "Light feeding every 2-3 weeks",
"growthRate": "Fast",
"matureSize": "15-30 cm tall",
"temperatureRange": "10°C - 22°C",
"toxicityLevel": "Non-toxic; edible crop",
"wateringFrequency": "Every 1-3 days depending on heat",
"careInstructions": "Harvest outer leaves first and protect from heat to prevent bolting.",
"commonProblems": "Bolting, slug damage, aphids, tip burn",
"propagationMethod": "Seed",
"nativeRegion": "Mediterranean and West Asia",
"plantBenefits": "Edible leaves, quick harvest, home garden suitable"
},
{ "nameAr": "فراولة",
"nameEn": "Strawberry",
"scientificName": "Fragaria × ananassa",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
"category": "Crops",
"careLevel": "medium",
"descriptionAr": "محصول محبوب ينتج ثماراً حمراء عطرية ولذيذة، ويمكن زراعته في الأرض أو الأصص. يحتاج شمساً جيدة ورياً منتظماً وتربة غنية جيدة الصرف.",
"descriptionEn": "A popular crop that produces fragrant, delicious red fruits and can be grown in the ground or pots. It needs good sun, regular watering, and fertile, well-draining soil.",
"waterRequirements": "Moderate - Keep soil evenly moist",
"lightRequirements": "Full sun",
"humidityRequirements": "Medium humidity, 50-70%",
"soilRequirements": "Rich, slightly acidic, well-draining soil",
"fertilizerRequirements": "Every 2-4 weeks during growth and fruiting",
"growthRate": "Moderate",
"matureSize": "15-25 cm tall, spreading by runners",
"temperatureRange": "10°C - 26°C",
"toxicityLevel": "Non-toxic; edible fruit",
"wateringFrequency": "Every 2-3 days in warm weather",
"careInstructions": "Mulch to keep fruits clean and remove old leaves regularly.",
"commonProblems": "Gray mold, slugs, aphids, crown rot",
"propagationMethod": "Runners or seedlings",
"nativeRegion": "Hybrid origin, cultivated widely",
"plantBenefits": "Edible fruit, container friendly, high value crop"
},
{ "nameAr": "سجاد الهند",
"nameEn": "Marigold",
"scientificName": "Tagetes erecta",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Tagetes_erecta_01.jpg",
"category": "Flower",
"careLevel": "easy",
"descriptionAr": "زهرة قوية وسهلة الزراعة بألوان صفراء وبرتقالية زاهية، وتُستخدم بكثرة في الزينة والحدائق. تمتاز بتحملها للشمس وجذبها للملقحات مع دور جيد في التنسيق الطبيعي للحدائق.",
"descriptionEn": "A hardy, easy-to-grow flower with bright yellow and orange blooms widely used in gardens and decoration. It tolerates sun well, attracts pollinators, and is useful in natural garden design.",
"waterRequirements": "Moderate - Water when the top soil dries slightly",
"lightRequirements": "Full sun",
"humidityRequirements": "Low to medium humidity",
"soilRequirements": "Well-draining fertile soil",
"fertilizerRequirements": "Light feeding once a month",
"growthRate": "Fast",
"matureSize": "20-90 cm depending on variety",
"temperatureRange": "18°C - 32°C",
"toxicityLevel": "Generally non-toxic",
"wateringFrequency": "Every 2-4 days in hot weather",
"careInstructions": "Deadhead regularly for continuous blooms.",
"commonProblems": "Aphids, powdery mildew, root rot, poor flowering in shade",
"propagationMethod": "Seed",
"nativeRegion": "Mexico",
"plantBenefits": "Ornamental color, pollinator friendly, easy garden use"
},
{ "nameAr": "زينيا",
"nameEn": "Zinnia",
"scientificName": "Zinnia elegans",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/88/Zinnia_elegans.jpg",
"category": "Flower",
"careLevel": "easy",
"descriptionAr": "زهرة صيفية قوية وسريعة الإزهار بألوان زاهية تناسب الحدائق المشمسة. تجذب الفراشات والملقحات وتناسب المبتدئين.",
"descriptionEn": "A strong, fast-blooming summer flower with bright colors suited to sunny gardens. It attracts butterflies and pollinators and is great for beginners.",
"waterRequirements": "Moderate - Water at the base when soil dries slightly",
"lightRequirements": "Full sun",
"humidityRequirements": "Low to medium humidity",
"soilRequirements": "Well-draining fertile soil",
"fertilizerRequirements": "Light feeding every 4 weeks",
"growthRate": "Fast",
"matureSize": "30-90 cm tall",
"temperatureRange": "18°C - 32°C",
"toxicityLevel": "Generally non-toxic",
"wateringFrequency": "Every 3-7 days depending on heat",
"careInstructions": "Deadhead spent blooms to keep flowering continuously.",
"commonProblems": "Powdery mildew, aphids, leaf spot, poor flowering in shade",
"propagationMethod": "Seed",
"nativeRegion": "Mexico",
"plantBenefits": "Pollinator support, vibrant color, easy seasonal display"
},
{ "nameAr": "ورد",
"nameEn": "Rose",
"scientificName": "Rosa × hybrida",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rose_flower.jpg",
"category": "Flower",
"careLevel": "medium",
"descriptionAr": "الورد من أشهر الزهور في العالم ويتميز بجمال ألوانه ورائحته واستخدامه الواسع في الزينة والهدايا. يزدهر مع الشمس الجيدة والتقليم المنتظم والتسميد المتوازن.",
"descriptionEn": "Roses are among the world’s most famous flowers, valued for their beauty, fragrance, and wide use in gifts and decoration. They thrive with good sun, regular pruning, and balanced feeding.",
"waterRequirements": "Moderate - Water deeply when the top layer dries",
"lightRequirements": "Full sun",
"humidityRequirements": "Medium humidity, 40-60%",
"soilRequirements": "Rich, well-draining loam with compost",
"fertilizerRequirements": "Every 2-4 weeks during the growing season",
"growthRate": "Moderate",
"matureSize": "0.5-2 meters depending on variety",
"temperatureRange": "15°C - 28°C",
"toxicityLevel": "Generally non-toxic",
"wateringFrequency": "Every 1-2 weeks",
"careInstructions": "Prune in the correct season and remove spent blooms regularly.",
"commonProblems": "Black spot, aphids, powdery mildew, poor flowering",
"propagationMethod": "Grafting or cuttings",
"nativeRegion": "Northern Hemisphere",
"plantBenefits": "Aesthetic, fragrance, ornamental and cut-flower use"
},
{ "nameAr": "بتونيا",
"nameEn": "Petunia",
"scientificName": "Petunia × atkinsiana",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Petunia_hybrida.jpg",
"category": "Flower",
"careLevel": "easy",
"descriptionAr": "زهرة موسمية غزيرة الإزهار تصلح للأحواض والشرفات والسلال المعلقة. ألوانها المتنوعة تجعلها خياراً ممتازاً للمناظر الزاهية طوال الموسم.",
"descriptionEn": "A prolific seasonal flower ideal for beds, balconies, and hanging baskets. Its wide color range makes it excellent for bright displays throughout the season.",
"waterRequirements": "Moderate - Keep soil lightly moist",
"lightRequirements": "Full sun",
"humidityRequirements": "Medium humidity, 40-60%",
"soilRequirements": "Well-draining, fertile potting mix",
"fertilizerRequirements": "Every 1-2 weeks with a bloom fertilizer",
"growthRate": "Fast",
"matureSize": "15-45 cm tall, trailing types longer",
"temperatureRange": "16°C - 30°C",
"toxicityLevel": "Generally non-toxic",
"wateringFrequency": "Every 2-3 days in hot weather, otherwise 1-2 times weekly",
"careInstructions": "Pinch tips for bushier growth and remove faded flowers.",
"commonProblems": "Aphids, powdery mildew, flower decline in heat, root rot",
"propagationMethod": "Seed or cuttings",
"nativeRegion": "South America",
"plantBenefits": "Long flowering, decorative color, balcony and garden use"
},
{ "nameAr": "ريحان",
"nameEn": "Basil",
"scientificName": "Ocimum basilicum",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Basil_(Ocimum_basilicum).jpg",
"category": "Herbs",
"careLevel": "easy",
"descriptionAr": "عشبة عطرية شهيرة تُستخدم في المطبخ وتُزرع بسهولة في الأصص أو الحدائق الصغيرة. تحتاج حرارة معتدلة وشمساً جيدة ورياً منتظماً دون إفراط.",
"descriptionEn": "A famous aromatic herb used in cooking and easy to grow in pots or small gardens. It prefers moderate warmth, good sun, and regular watering without excess.",
"waterRequirements": "Moderate - Keep soil lightly moist",
"lightRequirements": "Full sun to bright indirect light",
"humidityRequirements": "Medium humidity, 40-60%",
"soilRequirements": "Fertile, well-draining potting soil",
"fertilizerRequirements": "Light feeding every 3-4 weeks",
"growthRate": "Fast",
"matureSize": "20-60 cm tall",
"temperatureRange": "18°C - 30°C",
"toxicityLevel": "Non-toxic",
"wateringFrequency": "Every 2-4 days in warm weather",
"careInstructions": "Pinch tips often to prevent flowering and encourage bushy growth.",
"commonProblems": "Downy mildew, aphids, bolting, root rot",
"propagationMethod": "Seed or stem cuttings",
"nativeRegion": "Tropical Asia and Africa",
"plantBenefits": "Culinary use, fragrance, easy home growing"
},
{ "nameAr": "نعناع",
"nameEn": "Mint",
"scientificName": "Mentha spicata",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Apple_mint_plant.jpg",
"category": "Herbs",
"careLevel": "easy",
"descriptionAr": "عشبة قوية وسريعة الانتشار برائحة منعشة تُستخدم في الشاي والطهي. تنجح في الأصص أو الأرض الرطبة وتحتاج تقليماً دورياً حتى لا تنتشر بشكل مزعج.",
"descriptionEn": "A vigorous, fast-spreading herb with a refreshing scent used in tea and cooking. It grows well in pots or moist ground and needs regular trimming to keep it under control.",
"waterRequirements": "Moderate to high - Keep soil consistently moist",
"lightRequirements": "Full sun to partial shade",
"humidityRequirements": "Medium humidity, 40-70%",
"soilRequirements": "Rich, moist, well-draining soil",
"fertilizerRequirements": "Once a month during active growth",
"growthRate": "Fast",
"matureSize": "30-60 cm tall",
"temperatureRange": "12°C - 28°C",
"toxicityLevel": "Non-toxic",
"wateringFrequency": "Every 2-4 days",
"careInstructions": "Grow in containers to prevent spreading and harvest regularly.",
"commonProblems": "Rust, aphids, powdery mildew, over-spreading",
"propagationMethod": "Stem cuttings or division",
"nativeRegion": "Europe and Asia",
"plantBenefits": "Culinary use, fragrance, tea and garnish"
},
{ "nameAr": "إكليل الجبل",
"nameEn": "Rosemary",
"scientificName": "Salvia rosmarinus",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Rosemary_plant.jpg",
"category": "Herbs",
"careLevel": "medium",
"descriptionAr": "عشبة عطرية متحملة للجفاف ذات أوراق رفيعة ورائحة قوية تُستخدم في الطهي. تحب الشمس الكاملة والتربة الخفيفة جيدة التصريف.",
"descriptionEn": "A drought-tolerant aromatic herb with slender leaves and a strong scent used in cooking. It prefers full sun and light, well-draining soil.",
"waterRequirements": "Low to moderate - Allow soil to dry between waterings",
"lightRequirements": "Full sun",
"humidityRequirements": "Low humidity",
"soilRequirements": "Sandy, very well-draining soil",
"fertilizerRequirements": "Light feeding once or twice in spring and summer",
"growthRate": "Moderate",
"matureSize": "30-150 cm depending on variety",
"temperatureRange": "10°C - 30°C",
"toxicityLevel": "Non-toxic in small culinary amounts",
"wateringFrequency": "Every 1-2 weeks",
"careInstructions": "Avoid overwatering and prune lightly to keep it compact.",
"commonProblems": "Root rot, powdery mildew, aphids, slow growth in shade",
"propagationMethod": "Stem cuttings",
"nativeRegion": "Mediterranean region",
"plantBenefits": "Culinary use, fragrance, drought tolerance"
},
{ "nameAr": "بقدونس",
"nameEn": "Parsley",
"scientificName": "Petroselinum crispum",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Parsley.jpg",
"category": "Herbs",
"careLevel": "easy",
"descriptionAr": "عشبة مطبخ أساسية ذات أوراق خضراء غنية تُستخدم للتزيين والطهي. تنمو جيداً في الأحواض والشرفات وتفضل الري المنتظم والضوء الجيد.",
"descriptionEn": "A kitchen staple with rich green leaves used for cooking and garnish. It grows well in pots and balconies and prefers regular watering and good light.",
"waterRequirements": "Moderate - Keep soil evenly moist",
"lightRequirements": "Full sun to partial shade",
"humidityRequirements": "Medium humidity, 40-60%",
"soilRequirements": "Fertile, well-draining loam",
"fertilizerRequirements": "Every 3-4 weeks during growth",
"growthRate": "Moderate",
"matureSize": "20-40 cm tall",
"temperatureRange": "10°C - 25°C",
"toxicityLevel": "Non-toxic",
"wateringFrequency": "Every 2-4 days",
"careInstructions": "Harvest outer leaves first to encourage new growth.",
"commonProblems": "Aphids, leaf spot, bolting in heat, poor germination",
"propagationMethod": "Seed",
"nativeRegion": "Mediterranean region",
"plantBenefits": "Culinary use, garnish, nutrient-rich leaves"
},
{ "nameAr": "كزبرة",
"nameEn": "Coriander",
"scientificName": "Coriandrum sativum",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Coriandrum_sativum_plant.jpg",
"category": "Herbs",
"careLevel": "easy",
"descriptionAr": "عشبة سريعة النمو تُستخدم أوراقها وبذورها في المطبخ. تفضّل الجو المعتدل والري المنتظم، وتذهب سريعاً إلى الإزهار إذا ارتفعت الحرارة كثيراً.",
"descriptionEn": "A fast-growing herb used for both its leaves and seeds in cooking. It prefers mild temperatures and regular watering but bolts quickly in high heat.",
"waterRequirements": "Moderate - Keep soil lightly moist",
"lightRequirements": "Full sun to partial shade",
"humidityRequirements": "Medium humidity, 40-60%",
"soilRequirements": "Loose, well-draining fertile soil",
"fertilizerRequirements": "Light feeding once a month",
"growthRate": "Fast",
"matureSize": "20-60 cm tall",
"temperatureRange": "10°C - 25°C",
"toxicityLevel": "Non-toxic",
"wateringFrequency": "Every 2-4 days",
"careInstructions": "Sow in succession for continuous harvest and protect from intense heat.",
"commonProblems": "Bolting, aphids, leaf spot, poor germination",
"propagationMethod": "Seed",
"nativeRegion": "Southern Europe, North Africa, and Western Asia",
"plantBenefits": "Culinary use, fresh leaves, seed spice"
},
{ "nameAr": "أوريجانو",
"nameEn": "Oregano",
"scientificName": "Origanum vulgare",
"imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Origanum_vulgare_2014_G1.jpg",
"category": "Herbs",
"careLevel": "easy",
"descriptionAr": "عشبة عطرية قوية تستخدم كثيراً في أطباق البيتزا والصلصات. تتحمل الجفاف والحرارة المعتدلة وتناسب الزراعة في الأصص أو الحدائق الصخرية.",
"descriptionEn": "A strong aromatic herb widely used in pizza and sauces. It tolerates drought and moderate heat and suits pots or rock gardens well.",
"waterRequirements": "Low to moderate - Allow soil to dry slightly between waterings",
"lightRequirements": "Full sun",
"humidityRequirements": "Low to medium humidity",
"soilRequirements": "Well-draining sandy or loamy soil",
"fertilizerRequirements": "Minimal; light feeding once or twice during the season",
"growthRate": "Moderate",
"matureSize": "20-60 cm tall",
"temperatureRange": "15°C - 30°C",
"toxicityLevel": "Non-toxic in culinary amounts",
"wateringFrequency": "Every 1-2 weeks",
"careInstructions": "Trim regularly to keep plants compact and flavorful.",
"commonProblems": "Root rot, powdery mildew, aphids, weak growth in shade",
"propagationMethod": "Cuttings or division",
"nativeRegion": "Mediterranean region",
"plantBenefits": "Culinary use, aroma, drought tolerance"
} ];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI;
    if (!mongoUri) {
      console.error('No MONGO_URI found in env');
      process.exit(1);
    }
    
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    let addedCount = 0;
    let skippedCount = 0;

    for (const data of plantsData) {
      const slug = data.nameEn.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const existing = await Plant.findOne({ slug });
      
      let cleanImageUrl = data.imageUrl;
      if (cleanImageUrl.startsWith('[')) {
        const match = cleanImageUrl.match(/\[(.*?)\]/);
        if (match && match[1]) {
          cleanImageUrl = match[1];
        }
      }
      
      if (!existing) {
        await Plant.create({
          ...data,
          imageUrl: cleanImageUrl,
          slug,
          normalizedNameEn: data.nameEn.toLowerCase(),
          normalizedNameAr: data.nameAr.toLowerCase(),
          active: true,
          isLibraryItem: true,
          status: PlantStatus.PUBLISHED,
          createdBy: 'AI_SEEDER',
        });
        addedCount++;
        console.log(`Added: ${data.nameEn}`);
      } else {
        skippedCount++;
        console.log(`Skipped (already exists): ${data.nameEn}`);
      }
    }

    console.log(`Done! Added ${addedCount} plants, skipped ${skippedCount}.`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedDB();
