import Plant from "../models/plant_model";
import Disease from "../models/disease_model";
import User from "../models/user_model";
import bcrypt from "bcryptjs";

export const seedPlantLibrary = async () => {
  try {
    const plantCount = await Plant.countDocuments();
    if (plantCount === 0) {
      console.log("Seeding plants into the database...");
      const plantsWithSlug = seedPlants.map((p, i) => ({
        ...p,
        slug: p.nameEn.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + i,
        normalizedNameEn: p.nameEn.toLowerCase(),
        normalizedNameAr: p.nameAr,
      }));
      await Plant.create(plantsWithSlug);
      console.log("Plants seeded successfully.");
    }

    const diseaseCount = await Disease.countDocuments();
    if (diseaseCount === 0) {
      console.log("Seeding diseases into the database...");
      const diseasesWithSlug = seedDiseases.map((d, i) => ({
        ...d,
        slug: d.nameEn.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + i,
        normalizedNameEn: d.nameEn.toLowerCase(),
        normalizedNameAr: d.nameAr,
      }));
      await Disease.create(diseasesWithSlug);
      console.log("Diseases seeded successfully.");
    }
  } catch (error) {
    console.error("Failed to seed plant library database:", error);
  }
};

export const seedDefaultAdmin = async () => {
  try {
    const adminEmail = process.env.DEFAULT_ADMIN_EMAIL || "admin@nabatech.com";
    const adminPassword = process.env.DEFAULT_ADMIN_PASSWORD || "Admin1234";
    const adminName = process.env.DEFAULT_ADMIN_NAME || "Nabatech Admin";

    const exists = await User.findOne({ email: adminEmail });
    if (exists) return;

    const hashed = await bcrypt.hash(adminPassword, 10);
    await User.create({
      name: adminName,
      email: adminEmail,
      password: hashed,
      role: "admin",
    });

    console.log(`Default admin seeded: ${adminEmail}`);
  } catch (error) {
    console.error("Failed to seed default admin:", error);
  }
};

const seedPlants = [
  {
    nameAr: "فيكس ليراتا",
    nameEn: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    imageUrl: "https://images.unsplash.com/photo-1597055181300-e3633a0174ec?auto=format&fit=crop&q=80&w=800",
    category: "نباتات داخلية",
    careLevel: "medium",
    descriptionAr: "نبات زينة داخلي مشهور بأوراقه الكبيرة اللامعة، يحتاج عناية معتدلة وإضاءة جيدة.",
    descriptionEn: "A popular indoor ornamental plant with large glossy leaves that needs moderate care and good light.",
    waterRequirements: "Water thoroughly when the top 5-7 cm of soil becomes dry. Ensure excellent drainage to prevent root rot.",
    lightRequirements: "Bright, indirect sunlight. Can tolerate some morning direct sun, but harsh afternoon sun will scorch the leaves.",
    humidityRequirements: "Moderate to high (40%-60%). Mist leaves occasionally or use a humidifier in dry climates.",
    soilRequirements: "Well-draining, aerated potting mix. A mixture of peat, perlite, and pine bark is ideal.",
    fertilizerRequirements: "Feed with a balanced liquid houseplant fertilizer once a month during the growing season (spring and summer).",
    growthRate: "Moderate to fast during spring and summer.",
    matureSize: "Can reach 1.5 - 3 meters indoors.",
    temperatureRange: "18°C–29°C. Avoid cold drafts and sudden temperature drops.",
    toxicityLevel: "Mildly toxic to pets and humans if ingested (contains calcium oxalate crystals).",
    wateringFrequency: "Every 7-10 days depending on the season and indoor humidity.",
    careInstructions: "Wipe leaves regularly with a damp cloth to remove dust and improve photosynthesis. Rotate the plant monthly for even growth.",
    commonProblems: "Brown leaf edges (underwatering or low humidity), dropping leaves (overwatering or sudden environmental changes), and spider mites.",
    propagationMethod: "Stem cuttings propagated in water or soil, or air layering.",
    nativeRegion: "Western Africa",
    plantBenefits: "Excellent air purifier and adds a bold, structural aesthetic to indoor spaces."
  },
  {
    nameAr: "نبات الثعبان",
    nameEn: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    imageUrl: "https://images.unsplash.com/photo-1593482892290-f5619198eb53?auto=format&fit=crop&q=80&w=800",
    category: "سهلة العناية",
    careLevel: "easy",
    descriptionAr: "نبات قوي وسهل العناية، يتحمل الإهمال وقليل الإضاءة.",
    descriptionEn: "A tough, low-maintenance plant that tolerates neglect and low light conditions.",
    waterRequirements: "Allow the soil to dry out completely between waterings. Highly susceptible to overwatering.",
    lightRequirements: "Adaptable to all light conditions, from low indirect light to full direct sun.",
    humidityRequirements: "Low to average household humidity (20%-50%). Does not require misting.",
    soilRequirements: "Free-draining succulent or cactus mix containing coarse sand or pumice.",
    fertilizerRequirements: "Feed with a diluted succulent fertilizer once in spring and once in mid-summer.",
    growthRate: "Slow to moderate.",
    matureSize: "0.3 - 1.2 meters tall.",
    temperatureRange: "15°C–32°C. Keep away from frost.",
    toxicityLevel: "Mildly toxic to cats and dogs if ingested.",
    wateringFrequency: "Every 2-4 weeks. Water even less frequently during winter.",
    careInstructions: "Avoid getting water in the center rosette of the leaves. Wipe dust off the vertical leaves occasionally.",
    commonProblems: "Root rot from overwatering (leaves become mushy and fall over).",
    propagationMethod: "Leaf cuttings in soil or water, or by dividing the rhizomes.",
    nativeRegion: "West Africa",
    plantBenefits: "Releases oxygen at night (CAM photosynthesis) and filters indoor air toxins like formaldehyde and benzene."
  },
  {
    nameAr: "ألوفيرا",
    nameEn: "Aloe Vera",
    scientificName: "Aloe vera",
    imageUrl: "https://images.unsplash.com/photo-1596547609652-9cb5d8d73b22?auto=format&fit=crop&q=80&w=800",
    category: "سهلة العناية",
    careLevel: "easy",
    descriptionAr: "نبات عصاري معروف بفوائده الطبية واستخداماته في العناية بالبشرة.",
    descriptionEn: "A succulent plant known for medicinal benefits and common skincare uses.",
    waterRequirements: "Water deeply but infrequently. Allow the top 70% of the soil to dry completely before watering again.",
    lightRequirements: "Bright, indirect light to full sun. Insufficient light causes the leaves to stretch and weaken.",
    humidityRequirements: "Low (30%-40%). Thrives in dry, arid indoor environments.",
    soilRequirements: "Sandy, highly porous cactus or succulent soil mix to ensure rapid drainage.",
    fertilizerRequirements: "Rarely needs fertilizer. Apply a half-strength phosphorus-heavy fertilizer once in spring.",
    growthRate: "Moderate.",
    matureSize: "30 - 60 cm tall and wide.",
    temperatureRange: "13°C–27°C. Not frost-tolerant.",
    toxicityLevel: "Gel is safe topically, but the skin of the leaf is toxic to pets if ingested.",
    wateringFrequency: "Every 2-3 weeks in summer, and every 4-6 weeks in winter.",
    careInstructions: "Keep the plant in a heavy terracotta pot to prevent it from tipping over as it grows top-heavy.",
    commonProblems: "Root rot due to poor drainage, and soft, mushy leaves from overwatering.",
    propagationMethod: "Removing and replanting 'pups' (offsets) that grow from the base of the mother plant.",
    nativeRegion: "Arabian Peninsula",
    plantBenefits: "The gel inside the leaves can soothe minor burns, sunburns, and skin irritations."
  },
  {
    nameAr: "بيبروميا",
    nameEn: "Peperomia",
    scientificName: "Peperomia obtusifolia",
    imageUrl: "https://images.unsplash.com/photo-1620127599026-66f81a70cbbe?auto=format&fit=crop&q=80&w=800",
    category: "نباتات داخلية",
    careLevel: "easy",
    descriptionAr: "نبات صغير مناسب للمكاتب والمساحات الضيقة، سهل العناية.",
    descriptionEn: "A compact plant ideal for desks and small spaces, and very easy to care for.",
    waterRequirements: "Allow the top 5 cm of soil to dry out. The thick leaves store water, making them drought-tolerant.",
    lightRequirements: "Medium to bright indirect light. Direct sun can fade the leaf variegation and scorch the foliage.",
    humidityRequirements: "Average to high (40%-60%). Tolerates typical household humidity well.",
    soilRequirements: "Chunky, loose, and slightly acidic potting mix containing perlite and orchid bark.",
    fertilizerRequirements: "Apply a diluted liquid fertilizer monthly during the spring and summer.",
    growthRate: "Slow to moderate.",
    matureSize: "20 - 30 cm tall.",
    temperatureRange: "18°C–26°C. Keep away from cold drafts.",
    toxicityLevel: "Non-toxic and pet-safe.",
    wateringFrequency: "Every 7-14 days.",
    careInstructions: "Wipe leaves to keep them glossy. Prune leggy stems to encourage bushier growth.",
    commonProblems: "Fading leaves (too much light) or wilting/yellowing leaves (overwatering causing root rot).",
    propagationMethod: "Stem or leaf cuttings propagated in water or directly in moist soil.",
    nativeRegion: "Florida, Mexico, and the Caribbean",
    plantBenefits: "Safe for homes with pets and fits perfectly in small, confined desk spaces."
  },
  {
    nameAr: "مونستيرا",
    nameEn: "Monstera",
    scientificName: "Monstera deliciosa",
    imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&q=80&w=800",
    category: "نباتات داخلية",
    careLevel: "medium",
    descriptionAr: "نبات استوائي شهير بأوراقه المثقبة المميزة، يعطي مظهر عصري.",
    descriptionEn: "A popular tropical plant with signature split leaves that gives a modern look.",
    waterRequirements: "Water when the top 3-5 cm of the soil feels dry. Water thoroughly until it drains out the bottom.",
    lightRequirements: "Bright, indirect light. Too little light will result in small leaves without the iconic splits (fenestrations).",
    humidityRequirements: "Moderate to high (50%-80%). Thrives in humid environments.",
    soilRequirements: "A well-aerated, peat-based potting mix with perlite and bark to mimic its natural epiphytic environment.",
    fertilizerRequirements: "Balanced liquid fertilizer every 2-4 weeks during the growing season.",
    growthRate: "Fast during spring and summer.",
    matureSize: "1.5 - 3 meters indoors. Can grow much larger in the wild.",
    temperatureRange: "18°C–30°C.",
    toxicityLevel: "Mildly toxic to cats, dogs, and humans if the leaves or stems are ingested.",
    wateringFrequency: "Every 7-10 days, depending on light and temperature.",
    careInstructions: "Provide a moss pole or trellis for the aerial roots to climb. Clean leaves gently with a damp cloth.",
    commonProblems: "Yellowing leaves (overwatering) and brown, crispy edges (low humidity or underwatering).",
    propagationMethod: "Stem cuttings containing at least one node and aerial root, propagated in water.",
    nativeRegion: "Tropical forests of southern Mexico and Central America",
    plantBenefits: "Creates a dramatic, tropical aesthetic and filters indoor air."
  },
  {
    nameAr: "طماطم",
    nameEn: "Tomato",
    scientificName: "Solanum lycopersicum",
    imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307ba8?auto=format&fit=crop&q=80&w=800",
    category: "محاصيل",
    careLevel: "medium",
    descriptionAr: "نبات مثمر شائع يُزرع لإنتاج الطماطم ويحتاج عناية منتظمة.",
    descriptionEn: "A common fruiting crop grown for tomatoes and requiring consistent care.",
    waterRequirements: "Deep, consistent watering. Soil should be kept moist but not waterlogged. Irregular watering causes fruit splitting.",
    lightRequirements: "Full, direct sun. Requires at least 6-8 hours of direct sunlight daily to produce fruit.",
    humidityRequirements: "Moderate (40%-60%). High humidity can encourage fungal diseases like blight.",
    soilRequirements: "Rich, well-draining loamy soil with a slightly acidic pH (6.0 - 6.8).",
    fertilizerRequirements: "Heavy feeder. Use a fertilizer high in phosphorus and potassium once fruit sets.",
    growthRate: "Very fast.",
    matureSize: "Varies by variety; 1 - 2.5 meters tall.",
    temperatureRange: "21°C–29°C during the day. Stops setting fruit if temperatures exceed 32°C.",
    toxicityLevel: "Leaves and stems are toxic to pets. The ripe fruit is safe and edible.",
    wateringFrequency: "Every 1-2 days during hot summer months.",
    careInstructions: "Provide cages or stakes for support. Prune non-fruiting 'suckers' to direct energy to fruit production.",
    commonProblems: "Blossom end rot (calcium deficiency/uneven watering), aphids, and blight.",
    propagationMethod: "Grown from seeds or stem cuttings.",
    nativeRegion: "Western South America",
    plantBenefits: "Yields fresh, edible, highly nutritious fruits rich in lycopene and vitamin C."
  },
  {
    nameAr: "لافندر",
    nameEn: "Lavender",
    scientificName: "Lavandula",
    imageUrl: "https://images.unsplash.com/photo-1495908333425-29a1e0918c5f?auto=format&fit=crop&q=80&w=800",
    category: "نباتات مزهرة",
    careLevel: "easy",
    descriptionAr: "نبات عطري يستخدم في الزيوت العطرية وله رائحة مميزة مهدئة.",
    descriptionEn: "An aromatic plant used in essential oils with a distinctive calming fragrance.",
    waterRequirements: "Drought-tolerant once established. Water deeply when the top 5 cm of soil is completely dry.",
    lightRequirements: "Full, direct sun. Requires at least 6 hours of strong sunlight daily.",
    humidityRequirements: "Low (20%-40%). Highly susceptible to fungal issues in humid, stagnant air.",
    soilRequirements: "Lean, highly draining sandy or gravelly soil. Thrives in neutral to slightly alkaline pH.",
    fertilizerRequirements: "Do not over-fertilize. A light top-dressing of compost in early spring is sufficient.",
    growthRate: "Moderate.",
    matureSize: "30 - 90 cm tall and wide.",
    temperatureRange: "15°C–30°C. Many varieties are frost-hardy.",
    toxicityLevel: "Mildly toxic to cats and dogs if consumed in large quantities.",
    wateringFrequency: "Every 7-14 days. Reduce significantly during winter.",
    careInstructions: "Prune back by one-third after flowering to prevent the plant from becoming woody at the base.",
    commonProblems: "Root rot from poor drainage or overwatering. Fungal diseases in high humidity.",
    propagationMethod: "Hardwood or softwood cuttings.",
    nativeRegion: "Mediterranean region",
    plantBenefits: "Flowers attract pollinators. Essential oils have calming, anti-anxiety properties."
  },
  {
    nameAr: "بوتس",
    nameEn: "Pothos",
    scientificName: "Epipremnum aureum",
    imageUrl: "https://images.unsplash.com/photo-1600411832986-5a4477b64a1c?auto=format&fit=crop&q=80&w=800",
    category: "سهلة العناية",
    careLevel: "easy",
    descriptionAr: "نبات متسلق سهل العناية، مناسب للمبتدئين وينمو بسرعة.",
    descriptionEn: "An easy-care trailing plant, great for beginners and fast growing.",
    waterRequirements: "Water when the top 5 cm of soil feels dry. Tolerates occasional missed waterings easily.",
    lightRequirements: "Low to bright indirect light. Avoid direct harsh sun. Variegation is more pronounced in brighter light.",
    humidityRequirements: "Low to high (30%-70%). Highly adaptable to normal household air.",
    soilRequirements: "Standard, well-draining indoor potting soil.",
    fertilizerRequirements: "Diluted balanced liquid fertilizer once a month in spring and summer.",
    growthRate: "Fast.",
    matureSize: "Vines can trail for 2 - 3 meters indoors.",
    temperatureRange: "18°C–30°C. Keep above 10°C.",
    toxicityLevel: "Toxic to cats, dogs, and humans if ingested (causes oral irritation).",
    wateringFrequency: "Every 7-10 days.",
    careInstructions: "Pinch back long vines to encourage bushier growth at the base. Wipe leaves to remove dust.",
    commonProblems: "Yellow leaves from overwatering or poorly draining soil. Mealybugs occasionally.",
    propagationMethod: "Extremely easy to propagate via stem cuttings placed in water or soil.",
    nativeRegion: "Moorea (French Polynesia)",
    plantBenefits: "One of the best plants for removing indoor air pollutants like formaldehyde and xylene."
  },
  {
    nameAr: "زاميا",
    nameEn: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    imageUrl: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&q=80&w=800",
    category: "سهلة العناية",
    careLevel: "easy",
    descriptionAr: "نبات قوي جدًا يتحمل قلة الضوء والإهمال.",
    descriptionEn: "A very resilient plant that tolerates low light and neglect.",
    waterRequirements: "Allow the soil to dry out completely before watering. The rhizomes store water, making it highly drought-tolerant.",
    lightRequirements: "Adaptable to low indirect light, but grows faster in bright indirect light. Avoid direct afternoon sun.",
    humidityRequirements: "Low to average (20%-50%).",
    soilRequirements: "Well-draining mix containing perlite or sand to prevent moisture retention around rhizomes.",
    fertilizerRequirements: "Feed with a half-strength houseplant fertilizer twice a year (spring and summer).",
    growthRate: "Slow.",
    matureSize: "60 - 90 cm tall.",
    temperatureRange: "18°C–29°C. Do not expose to temperatures below 10°C.",
    toxicityLevel: "Toxic to pets and humans if ingested.",
    wateringFrequency: "Every 2-3 weeks.",
    careInstructions: "Dust the glossy leaves periodically with a damp cloth. Do not use leaf shine products.",
    commonProblems: "Yellowing lower leaves and mushy stems are signs of severe overwatering.",
    propagationMethod: "Leaf cuttings or rhizome division (very slow process).",
    nativeRegion: "Eastern Africa",
    plantBenefits: "Virtually indestructible, thrives in low-light offices, and purifies indoor air."
  },
  {
    nameAr: "جهنمية",
    nameEn: "Bougainvillea",
    scientificName: "Bougainvillea spectabilis",
    imageUrl: "https://images.unsplash.com/photo-1599383637775-8fb9d6439fc7?auto=format&fit=crop&q=80&w=800",
    category: "نباتات خارجية",
    careLevel: "medium",
    descriptionAr: "نبات متسلق مزهر بألوان زاهية يستخدم في الحدائق.",
    descriptionEn: "A flowering climber with vivid colors, widely used in gardens.",
    waterRequirements: "Water deeply when the top layer of soil dries out. Prefers to be kept slightly on the dry side to encourage blooming.",
    lightRequirements: "Full, direct sun. Needs at least 6 hours of sun to produce vibrant bracts.",
    humidityRequirements: "Low to moderate. Highly drought-tolerant.",
    soilRequirements: "Well-draining, slightly acidic soil. Will fail to thrive in heavy, waterlogged clay.",
    fertilizerRequirements: "Use a high-potassium, low-nitrogen fertilizer during the blooming season to encourage flowers over foliage.",
    growthRate: "Fast.",
    matureSize: "Can climb up to 4 - 9 meters outdoors.",
    temperatureRange: "18°C–35°C. Sensitive to frost; must be brought indoors if temperatures drop near freezing.",
    toxicityLevel: "Sap is mildly toxic. The thorns can cause skin irritation or physical injury.",
    wateringFrequency: "Every 5-7 days outdoors in summer. Reduce drastically in winter.",
    careInstructions: "Prune vigorously after blooming cycles to shape the plant and encourage new growth where flowers form.",
    commonProblems: "Lack of flowers (usually due to too much water or not enough direct sunlight). Aphids and caterpillars.",
    propagationMethod: "Hardwood or semi-hardwood stem cuttings.",
    nativeRegion: "South America (Brazil, Peru, Argentina)",
    plantBenefits: "Provides spectacular, long-lasting color for trellises, walls, and fences."
  },
  {
    nameAr: "ياسمين",
    nameEn: "Jasmine",
    scientificName: "Jasminum officinale",
    imageUrl: "https://images.unsplash.com/photo-1596752044810-67c13da82ad0?auto=format&fit=crop&q=80&w=800",
    category: "نباتات خارجية",
    careLevel: "medium",
    descriptionAr: "نبات عطري مزهر مشهور برائحته الجميلة ويستخدم في الحدائق والعطور.",
    descriptionEn: "A fragrant flowering plant known for its beautiful scent and use in gardens and perfumes.",
    waterRequirements: "Keep the soil evenly moist but not soggy during the growing season.",
    lightRequirements: "Full sun to partial shade. Prefers morning sun and afternoon shade in hot climates.",
    humidityRequirements: "Moderate to high (50%-70%). Indoors, use a humidity tray.",
    soilRequirements: "Rich, loamy, and well-draining soil with plenty of organic compost.",
    fertilizerRequirements: "Apply a phosphorus-rich liquid fertilizer every two weeks during spring and summer to boost blooms.",
    growthRate: "Fast-growing vine.",
    matureSize: "Can climb up to 3 - 4.5 meters outdoors.",
    temperatureRange: "15°C–26°C. Provide cooler temperatures in autumn to encourage winter/spring blooming.",
    toxicityLevel: "Non-toxic to pets and humans.",
    wateringFrequency: "Every 3-5 days outdoors in the heat. Check soil moisture regularly.",
    careInstructions: "Provide a sturdy trellis for support. Prune immediately after flowering to control size and shape.",
    commonProblems: "Spider mites in dry air, and bud drop if the soil is too dry or too wet.",
    propagationMethod: "Semi-hardwood cuttings taken in summer.",
    nativeRegion: "Caucasus, northern Iran, Afghanistan, and the Himalayas",
    plantBenefits: "Intensely sweet, relaxing fragrance. Often used to make soothing teas and essential oils."
  },
  {
    nameAr: "نبات العنكبوت",
    nameEn: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    imageUrl: "https://images.unsplash.com/photo-1613567784651-7870a3c267c8?auto=format&fit=crop&q=80&w=800",
    category: "نباتات داخلية",
    careLevel: "easy",
    descriptionAr: "نبات داخلي سهل العناية يتميز بأوراقه الطويلة وينتج نباتات صغيرة.",
    descriptionEn: "An easy indoor plant with long leaves that produces small offshoots.",
    waterRequirements: "Water moderately, allowing the top 3 cm of soil to dry out. It has tuberous roots that store water.",
    lightRequirements: "Bright, indirect light. Direct sun will scorch the leaves, while deep shade slows growth and fading stripes.",
    humidityRequirements: "Moderate (40%-60%). Brown leaf tips often indicate low humidity.",
    soilRequirements: "Standard, well-draining indoor potting mix.",
    fertilizerRequirements: "Diluted balanced fertilizer once a month during spring and summer. Do not over-fertilize.",
    growthRate: "Fast.",
    matureSize: "30 - 60 cm tall and wide.",
    temperatureRange: "15°C–29°C.",
    toxicityLevel: "Non-toxic and completely pet-safe.",
    wateringFrequency: "Every 7-10 days. Prefers distilled water to avoid fluoride tip-burn.",
    careInstructions: "Allow the 'spiderettes' (babies) to hang freely. Repot when the thick roots push the plant out of its pot.",
    commonProblems: "Crispy brown leaf tips from tap water impurities (fluoride/chlorine) or dry air.",
    propagationMethod: "Planting the small 'spiderettes' (pups) that grow on long trailing stems.",
    nativeRegion: "Tropical and Southern Africa",
    plantBenefits: "Safe for cats/dogs and highly effective at clearing indoor air of formaldehyde and xylene."
  },
  {
    nameAr: "أوركيد",
    nameEn: "Orchid",
    scientificName: "Phalaenopsis",
    imageUrl: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&q=80&w=800",
    category: "نباتات مزهرة",
    careLevel: "hard",
    descriptionAr: "نبات مزهر فاخر يحتاج عناية خاصة وظروف دقيقة لينمو بشكل جيد.",
    descriptionEn: "A premium flowering plant that needs special care and precise growing conditions.",
    waterRequirements: "Water thoroughly by running water through the pot for a minute, then let it drain completely. Never let roots sit in water.",
    lightRequirements: "Bright, indirect light. Direct sun easily burns the leaves. An east-facing window is ideal.",
    humidityRequirements: "High (50%-70%). Use a humidity tray with pebbles and water beneath the pot.",
    soilRequirements: "Requires an epiphytic mix: coarse bark, sphagnum moss, and perlite. DO NOT use regular potting soil.",
    fertilizerRequirements: "Use a specialized orchid fertilizer weakly (quarter strength) every time you water.",
    growthRate: "Slow.",
    matureSize: "30 - 70 cm tall including the flower spike.",
    temperatureRange: "18°C–29°C during the day. A slight temperature drop at night encourages blooming.",
    toxicityLevel: "Non-toxic to pets and humans.",
    wateringFrequency: "Every 7-10 days. Wait until the thick green roots turn silvery-gray before watering.",
    careInstructions: "Cut the flower spike down to the base once all flowers have fallen off to direct energy into new leaf and root growth.",
    commonProblems: "Crown rot from water sitting in the center of the leaves. Shriveled leaves indicate dead roots from overwatering.",
    propagationMethod: "Keikis (baby plants) that occasionally grow on the flower spikes.",
    nativeRegion: "Southeast Asia and Northern Australia",
    plantBenefits: "Produces stunning, long-lasting elegant blooms that can stay open for up to 3 months."
  },
  {
    nameAr: "شجرة الليمون",
    nameEn: "Lemon Tree",
    scientificName: "Citrus limon",
    imageUrl: "https://images.unsplash.com/photo-1561570183-b77da1b17e4f?auto=format&fit=crop&q=80&w=800",
    category: "محاصيل",
    careLevel: "medium",
    descriptionAr: "شجرة مثمرة تنتج الليمون وتحتاج إلى ضوء قوي وعناية منتظمة.",
    descriptionEn: "A fruit tree that produces lemons and needs strong light and regular care.",
    waterRequirements: "Keep soil moist but never soggy. Allow the top 5 cm of soil to dry before watering deeply.",
    lightRequirements: "Full, direct sun. Needs 8-12 hours of sunlight daily for healthy fruit production.",
    humidityRequirements: "Moderate (50%). Indoors, it benefits heavily from regular misting or a humidifier.",
    soilRequirements: "Slightly acidic, well-draining sandy loam. Commercial citrus mixes work best for potted trees.",
    fertilizerRequirements: "Use a specialized citrus fertilizer high in nitrogen and containing micronutrients (iron, zinc, manganese) every 4-6 weeks.",
    growthRate: "Moderate.",
    matureSize: "1.5 - 3 meters in a pot; larger outdoors.",
    temperatureRange: "18°C–30°C. Protect from temperatures below 10°C.",
    toxicityLevel: "The fruit is edible, but leaves, stems, and peels contain essential oils toxic to cats and dogs.",
    wateringFrequency: "Every 5-7 days outdoors in summer, less frequently indoors or in winter.",
    careInstructions: "If kept indoors, you must hand-pollinate the fragrant white flowers using a small brush to get fruit.",
    commonProblems: "Yellowing leaves with green veins (iron deficiency). Scale insects and spider mites.",
    propagationMethod: "Grafting or semi-hardwood cuttings. Seeds rarely grow true to the parent plant.",
    nativeRegion: "South Asia (Northeastern India)",
    plantBenefits: "Yields fresh, acidic fruits rich in Vitamin C, and the blossoms perfume the entire room."
  },
  {
    nameAr: "نعناع",
    nameEn: "Mint",
    scientificName: "Mentha",
    imageUrl: "https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?auto=format&fit=crop&q=80&w=800",
    category: "مأكولات",
    careLevel: "easy",
    descriptionAr: "نبات عطري سريع النمو يستخدم في الطعام والمشروبات.",
    descriptionEn: "A fast-growing aromatic herb commonly used in foods and drinks.",
    waterRequirements: "Requires consistently moist soil. Do not allow the soil to dry out completely, but ensure proper drainage.",
    lightRequirements: "Full sun to partial shade. In very hot climates, afternoon shade prevents wilting.",
    humidityRequirements: "Moderate. Does well in most environments as long as soil moisture is maintained.",
    soilRequirements: "Rich, loamy, and moist soil. Add compost to retain moisture.",
    fertilizerRequirements: "Feed lightly with a balanced, water-soluble organic fertilizer every 4-6 weeks. Over-fertilizing dilutes the flavor.",
    growthRate: "Extremely fast and aggressive.",
    matureSize: "30 - 60 cm tall, spreads infinitely if not contained.",
    temperatureRange: "12°C–25°C. Frost hardy depending on the variety.",
    toxicityLevel: "Non-toxic to humans, but essential oils can cause mild upset stomach in pets if large amounts are eaten.",
    wateringFrequency: "Every 2-3 days, more frequently in extreme heat or small pots.",
    careInstructions: "Always grow mint in containers! If planted directly in the ground, it will aggressively take over the garden. Harvest leaves frequently to encourage bushy growth.",
    commonProblems: "Rust (fungal disease causing orange spots) and powdery mildew. Spider mites in dry conditions.",
    propagationMethod: "Root division, runner separation, or stem cuttings in water.",
    nativeRegion: "Eurasia, North America, and southern Africa",
    plantBenefits: "Highly versatile culinary herb, excellent for teas and garnishes. Its strong scent repels some garden pests."
  },
  {
    nameAr: "عباد الشمس",
    nameEn: "Sunflower",
    scientificName: "Helianthus annuus",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&q=80&w=800",
    category: "نباتات مزهرة",
    careLevel: "easy",
    descriptionAr: "نبات سنوي طويل يُعرف بأزهاره الصفراء الكبيرة التي تتتبع الشمس.",
    descriptionEn: "A tall annual plant known for its large yellow flowers that track the sun.",
    waterRequirements: "Water deeply and infrequently. Their deep taproots make them relatively drought-tolerant once established.",
    lightRequirements: "Full, unobstructed direct sun. Needs 6-8 hours minimum for sturdy stalks and large blooms.",
    humidityRequirements: "Low to moderate. High humidity can cause fungal diseases.",
    soilRequirements: "Loose, well-draining soil. They are not overly picky about soil quality but prefer slightly alkaline conditions.",
    fertilizerRequirements: "Heavy feeders. Apply a slow-release, phosphorus-rich fertilizer when planting, and a liquid feed when flower buds form.",
    growthRate: "Very fast.",
    matureSize: "1 - 3.5 meters tall depending on the variety.",
    temperatureRange: "21°C–29°C. Seeds need warm soil (above 15°C) to germinate.",
    toxicityLevel: "Non-toxic to humans, cats, dogs, and horses.",
    wateringFrequency: "Every 4-7 days depending on heat and rainfall. Water at the base, not on the leaves.",
    careInstructions: "Tall varieties require staking to protect them from high winds. Deadhead smaller varieties to encourage continuous blooming.",
    commonProblems: "Powdery mildew on leaves, rust, and pests like aphids and caterpillars.",
    propagationMethod: "Grown from seeds sown directly into the soil after the last frost.",
    nativeRegion: "North America",
    plantBenefits: "Produces edible, nutritious seeds. The massive flowers attract bees and birds to the garden."
  },
  {
    nameAr: "الكركديه",
    nameEn: "Hibiscus",
    scientificName: "Hibiscus sabdariffa",
    imageUrl: "https://images.unsplash.com/photo-1555581977-154df66c7471?auto=format&fit=crop&q=80&w=800",
    category: "نباتات مزهرة",
    careLevel: "medium",
    descriptionAr: "نبات استوائي جميل بأزهار حمراء كبيرة، يُستخدم لصنع الشاي.",
    descriptionEn: "A beautiful tropical plant with large red flowers, used for making tea.",
    waterRequirements: "Requires consistent moisture, especially when blooming. Do not let the soil completely dry out, but ensure it drains well.",
    lightRequirements: "Full sun. It requires at least 6-8 hours of direct sunlight daily to produce abundant flowers.",
    humidityRequirements: "High (60%+). Thrives in warm, humid tropical environments.",
    soilRequirements: "Rich, well-draining, slightly acidic soil (pH 5.5 - 6.5).",
    fertilizerRequirements: "Use a balanced liquid fertilizer or a slow-release formula high in potassium every two weeks during summer.",
    growthRate: "Fast.",
    matureSize: "1 - 2.5 meters tall and wide.",
    temperatureRange: "15°C–32°C. Not frost-tolerant. Needs to be brought indoors in freezing winter climates.",
    toxicityLevel: "Non-toxic to humans and pets.",
    wateringFrequency: "Every 1-3 days in hot weather.",
    careInstructions: "Pinch the tips of young plants to encourage branching. Prune heavily in early spring to maintain shape.",
    commonProblems: "Bud drop (caused by extreme temperature changes or irregular watering), aphids, and whiteflies.",
    propagationMethod: "Stem cuttings or from seed.",
    nativeRegion: "West Africa",
    plantBenefits: "The fleshy red calyces are harvested to make a tart, ruby-red herbal tea rich in antioxidants."
  },
  {
    nameAr: "الورد",
    nameEn: "Rose",
    scientificName: "Rosa damascena",
    imageUrl: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&q=80&w=800",
    category: "نباتات مزهرة",
    careLevel: "medium",
    descriptionAr: "ملكة الأزهار، معروفة برائحتها الزكية والألوان الجميلة.",
    descriptionEn: "Queen of flowers, known for fragrance and beautiful colors.",
    waterRequirements: "Water deeply at the base of the plant once or twice a week. Keep foliage dry to prevent fungal diseases.",
    lightRequirements: "Full sun. At least 6-8 hours of direct morning sun is necessary for strong blooming.",
    humidityRequirements: "Moderate. Needs good air circulation around the leaves.",
    soilRequirements: "Rich, loamy, well-draining soil with plenty of organic matter. Mildly acidic pH.",
    fertilizerRequirements: "Feed with a specialized rose fertilizer (high phosphorus) every 4-6 weeks from spring through late summer.",
    growthRate: "Moderate.",
    matureSize: "1 - 2 meters tall.",
    temperatureRange: "15°C–26°C. Tolerates freezing winters when dormant.",
    toxicityLevel: "Non-toxic, but the sharp thorns pose a physical hazard.",
    wateringFrequency: "Every 3-5 days in dry heat, focusing water directly onto the soil.",
    careInstructions: "Prune bushes dramatically in late winter/early spring to remove dead wood and open the center to airflow. Deadhead spent blooms.",
    commonProblems: "Black spot fungus, powdery mildew, and aphids. Requires vigilant pest and disease management.",
    propagationMethod: "Stem cuttings, grafting, or layering.",
    nativeRegion: "Middle East and Asia",
    plantBenefits: "Produces highly prized, intensely fragrant flowers used for rose water, essential oils, and ornamental beauty."
  },
  {
    nameAr: "الريحان",
    nameEn: "Basil",
    scientificName: "Ocimum basilicum",
    imageUrl: "https://images.unsplash.com/photo-1606859191834-bd12c9fbdb65?auto=format&fit=crop&q=80&w=800",
    category: "مأكولات",
    careLevel: "easy",
    descriptionAr: "عشبة عطرية شهيرة تُستخدم في الطهي، سهلة الزراعة.",
    descriptionEn: "A famous aromatic herb used in cooking, easy to grow.",
    waterRequirements: "Keep the soil consistently moist. Water when the top 2-3 cm feels dry. Drooping leaves clearly indicate thirst.",
    lightRequirements: "Full sun. Requires 6-8 hours of direct sunlight. Indoors, place on a sunny south-facing windowsill.",
    humidityRequirements: "Moderate (40%-60%). Requires good air circulation.",
    soilRequirements: "Rich, well-draining, slightly acidic soil mixed with plenty of compost.",
    fertilizerRequirements: "Feed lightly with a balanced liquid fertilizer every 3-4 weeks. Excessive fertilizer weakens the flavor.",
    growthRate: "Fast.",
    matureSize: "30 - 60 cm tall.",
    temperatureRange: "21°C–32°C. Extremely sensitive to cold. Will blacken and die at the first sign of frost.",
    toxicityLevel: "Non-toxic to pets and humans. Edible and highly nutritious.",
    wateringFrequency: "Every 2-3 days, depending on the heat.",
    careInstructions: "Harvest leaves frequently from the top. Pinch off any flower buds immediately to prevent the leaves from becoming bitter.",
    commonProblems: "Downy mildew (causes yellowing leaves and fuzzy gray undersides), aphids, and slugs.",
    propagationMethod: "Grown from seeds or stem cuttings rooted in water.",
    nativeRegion: "Central Africa and Southeast Asia",
    plantBenefits: "A staple culinary herb that pairs perfectly with tomatoes and is the foundation for pesto."
  }
];

const seedDiseases = [
  {
    nameAr: "البياض الدقيقي",
    nameEn: "Powdery Mildew",
    imageUrl: "https://images.unsplash.com/photo-1629198642307-2a54ce6e1291?q=80&w=800&auto=format&fit=crop",
    severity: "medium",
    type: "Fungal",
    affectedPlantsCount: 120,
    descriptionAr: "مرض فطري يسبب طبقة بيضاء مسحوقية على سطح الأوراق. يظهر غالبا مع الرطوبة العالية.",
    descriptionEn: "A fungal disease causing a powdery white layer on leaf surfaces. Often appears in high humidity."
  },
  {
    nameAr: "تبقع الأوراق البكتيري",
    nameEn: "Bacterial Leaf Spot",
    imageUrl: "https://images.unsplash.com/photo-1587841198424-df3abfdb4a39?q=80&w=800&auto=format&fit=crop",
    severity: "high",
    type: "Bacterial",
    affectedPlantsCount: 85,
    descriptionAr: "يسبب بقعا داكنة على الأوراق وقد يؤدي إلى تساقطها المبكر.",
    descriptionEn: "Causes dark spots on leaves and can lead to premature leaf drop."
  },
  {
    nameAr: "عفن الجذور",
    nameEn: "Root Rot",
    imageUrl: "https://images.unsplash.com/photo-1601633512211-1ad52b6357cc?q=80&w=800&auto=format&fit=crop",
    severity: "high",
    type: "Fungal",
    affectedPlantsCount: 200,
    descriptionAr: "ينتج غالبا عن زيادة الري وضعف التصريف، فتتحول الجذور إلى اللون البني.",
    descriptionEn: "Often results from overwatering and poor drainage, causing roots to turn brown."
  },
  {
    nameAr: "تآكل الأوراق",
    nameEn: "Leaf Miners",
    imageUrl: "https://images.unsplash.com/photo-1596484391307-fcf873ffbd4f?q=80&w=800&auto=format&fit=crop",
    severity: "low",
    type: "Pest",
    affectedPlantsCount: 45,
    descriptionAr: "حشرة تضع بيضها داخل الأوراق وتترك خطوطا متعرجة بيضاء أثناء تغذيها.",
    descriptionEn: "An insect that lays eggs inside leaves, leaving winding white trails as it feeds."
  },
  {
    nameAr: "حشرة المن",
    nameEn: "Aphids",
    imageUrl: "https://images.unsplash.com/photo-1621379374092-23f2f01f074d?q=80&w=800&auto=format&fit=crop",
    severity: "medium",
    type: "Pest",
    affectedPlantsCount: 300,
    descriptionAr: "حشرات صغيرة تمتص عصارة النبات وتسبب اصفرار الأوراق وضعف النمو.",
    descriptionEn: "Small insects that suck plant sap, causing leaves to yellow and weakening growth."
  },
  {
    nameAr: "العنكبوت الأحمر",
    nameEn: "Spider Mites",
    imageUrl: "https://images.unsplash.com/photo-1607518534882-628d63aab74a?q=80&w=800&auto=format&fit=crop",
    severity: "high",
    type: "Pest",
    affectedPlantsCount: 180,
    descriptionAr: "آفة دقيقة تنشط في الجو الحار، تترك نقطا صفراء وشبكات خفيفة على الأوراق.",
    descriptionEn: "A tiny pest active in hot weather, leaving yellow spots and light webbing on leaves."
  }
];


