"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_middleware_1 = require("../middlewares/auth_middleware");
var ai_models_controller_1 = require("../controllers/ai_models_controller");
var router = (0, express_1.Router)();
router.get("/manifest", ai_models_controller_1.getAiModelsManifest);
router.get("/manifest/:id/proxy-url", auth_middleware_1.protect, ai_models_controller_1.getAiModelProxyUrl);
router.post("/manifest", auth_middleware_1.protect, auth_middleware_1.admin, ai_models_controller_1.createAiModelManifestItem);
router.put("/manifest/:id", auth_middleware_1.protect, auth_middleware_1.admin, ai_models_controller_1.updateAiModelManifestItem);
router.delete("/manifest/:id", auth_middleware_1.protect, auth_middleware_1.admin, ai_models_controller_1.deleteAiModelManifestItem);
exports.default = router;
