"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_middleware_1 = require("../middlewares/auth_middleware");
var ai_settings_controller_1 = require("../controllers/ai_settings_controller");
var router = (0, express_1.Router)();
router.get("/", auth_middleware_1.protect, auth_middleware_1.admin, ai_settings_controller_1.getAdminAiSettings);
router.put("/", auth_middleware_1.protect, auth_middleware_1.admin, ai_settings_controller_1.putAdminAiSettings);
router.post("/test", auth_middleware_1.protect, auth_middleware_1.admin, ai_settings_controller_1.testAdminAiSettings);
router.get("/logs", auth_middleware_1.protect, auth_middleware_1.admin, ai_settings_controller_1.getAdminAiLogs);
exports.default = router;
