"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_middleware_1 = require("../middlewares/auth_middleware");
var chat_controller_1 = require("../controllers/chat_controller");
var rate_limit_middleware_1 = require("../middlewares/rate_limit_middleware");
var router = (0, express_1.Router)();
router.post("/", rate_limit_middleware_1.aiRateLimiter, auth_middleware_1.protect, chat_controller_1.chatWithAI);
router.post("/feedback", auth_middleware_1.protect, chat_controller_1.submitFeedback);
router.get("/history", auth_middleware_1.protect, chat_controller_1.getChatHistory);
router.get("/sessions", auth_middleware_1.protect, chat_controller_1.getChatSessions);
router.get("/all", auth_middleware_1.protect, auth_middleware_1.admin, chat_controller_1.getAllChatLogs);
exports.default = router;
