"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var diary_controller_1 = require("../controllers/diary_controller");
var auth_middleware_1 = require("../middlewares/auth_middleware");
var router = (0, express_1.Router)();
router.get("/", auth_middleware_1.protect, diary_controller_1.getDiaryEntries);
router.post("/", auth_middleware_1.protect, diary_controller_1.createDiaryEntry);
router.put("/:id", auth_middleware_1.protect, diary_controller_1.updateDiaryEntry);
router.delete("/:id", auth_middleware_1.protect, diary_controller_1.deleteDiaryEntry);
exports.default = router;
