"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var history_controller_1 = require("../controllers/history_controller");
var auth_middleware_1 = require("../middlewares/auth_middleware");
var validate_request_middleware_1 = require("../middlewares/validate_request_middleware");
var history_schemas_1 = require("../validation/history_schemas");
var router = (0, express_1.Router)();
router.get("/", auth_middleware_1.protect, (0, validate_request_middleware_1.validateRequest)(history_schemas_1.historyQuerySchema), history_controller_1.getHistory);
router.get("/:id", auth_middleware_1.protect, history_controller_1.getDiagnosisById);
router.delete("/:id", auth_middleware_1.protect, history_controller_1.deleteDiagnosis);
router.delete("/", auth_middleware_1.protect, (0, validate_request_middleware_1.validateRequest)(history_schemas_1.clearHistoryQuerySchema), history_controller_1.clearHistory);
router.put("/:id/feedback", auth_middleware_1.protect, (0, validate_request_middleware_1.validateRequest)(history_schemas_1.updateFeedbackSchema), history_controller_1.updateFeedback);
exports.default = router;
